A/A/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',  include('accounts.urls', namespace='accounts')),
    path('', include('home.urls', namespace='home')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

A/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout'),
    path('profile/<int:user_id>/', views.UserProfileView.as_view(), name='user_profile'),
    path('reset/', views.UserPasswordRestView.as_view(), name='reset_password'),
    path('reset/done/', views.UserPasswordRestDoneView.as_view(), name='password_reset_done'),
    path('confirm/<uidb64>/<token>/', views.UserPasswordRestConfirmView.as_view(), name='password_reset_confirm'),
    path('confirm/complete/', views.UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('follow/<int:user_id>/', views.UserFollowView.as_view(), name='user_follow'),
    path('unfollow/<int:user_id>/', views.UserUnfollowView.as_view(), name='user_unfollow'),
]

A/home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('post_create/', views.PostCreateView.as_view(), name='post_create'),
    path('post/detail/<int:post_id>/<slug:post_slug>/', views.PostDetailView.as_view(), name='post_detail'),
    path('post/update/<int:post_id>/', views.PostUpdateView.as_view(), name='post_update'),
    path('post/delete/<int:post_id>/', views.PostDeleteView.as_view(), name='post_delete'),

]

A/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from .managers import UserManager


class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=50)
    email = models.EmailField(max_length=255, unique=True)
    phone_number = models.CharField(max_length=11, unique=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'phone_number'
    REQUIRED_FIELDS = ['email', 'username']

    def __str__(self):
        return self.username

    @property
    def is_staff(self):
        return self.is_admin


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    age = models.PositiveIntegerField(default=0)
    bio = models.TextField(null=True, blank=True)


class Relation(models.Model):
    from_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='followers')
    to_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='following')
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.from_user} following {self.to_user}'

A/accounts/forms.py
from django import forms
from .models import User
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import ReadOnlyPasswordHashField


class UserCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email', 'phone_number', 'username')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password1'] and cd['password2'] and cd['password1'] != cd['password2']:
            raise ValidationError('passwords dont match')
        return cd['password2']

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField(help_text="you can change password using <a href=\"../password/\">this form</a>.")

    class Meta:
        model = User
        fields = ('email', 'phone_number', 'username', 'password', 'last_login')


class UserRegisterForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    phone = forms.CharField(max_length=11, widget=forms.TextInput(attrs={'class': 'form-control'}))
    username = forms.CharField(label='name', widget=forms.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label='password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label='password confirm', widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    def clean_email(self):
        email = self.cleaned_data['email']
        user = User.objects.filter(email=email).exists()
        if user:
            raise ValidationError('This email already exists!')
        return email

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        user = User.objects.filter(phone_number=phone).exists()
        if user:
            raise ValidationError('This phone number already exists!')
        return phone

    def clean(self):
        cd = super().clean()
        p1 = cd.get('password1')
        p2 = cd.get('password2')

        if p1 and p2 and p1 != p2:
            raise ValidationError('password must match!')


class UserLoginForm(forms.Form):
    phone = forms.CharField(max_length=11)
    password = forms.CharField(widget=forms.PasswordInput)

A/accounts/views.py
from django.shortcuts import render, redirect
from django.views import View
from .forms import UserRegisterForm, UserLoginForm
from .models import User, Relation
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy


class UserRegisterView(View):
    form_class = UserRegisterForm
    template_name = 'accounts/register.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        form = self.form_class
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            User.objects.create_user(cd['phone'], cd['email'], cd['username'], cd['password1'])
            messages.success(request, 'you registered successfully', 'success')
            return redirect('home:home')
        return render(request, self.template_name, {'form': form})


class UserLoginView(View):
    form_class = UserLoginForm
    template_name = 'accounts/login.html'

    def setup(self, request, *args, **kwargs):
        self.next = request.GET.get('next')
        return super().setup(request, *args, **kwargs)

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        form = self.form_class
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, phone_number=cd['phone'], password=cd['password'])
            if user is not None:
                login(request, user)
                messages.success(request, 'you logged in successfully.', 'success')
                if self.next:
                    return redirect(self.next)
                return redirect('home:home')
            messages.error(request, 'username or password does not exist.', 'warning')
        return render(request, self.template_name, {'form': form})


class UserLogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        messages.success(request, 'you logged out successfully.', 'success')
        return redirect('home:home')


class UserProfileView(LoginRequiredMixin, View):
    def get(self, request, user_id):
        is_following = False
        user = User.objects.get(pk=user_id)
        posts = user.posts.all()
        relation = Relation.objects.filter(from_user=request.user, to_user=user)
        if relation.exists():
            is_following = True
        return render(request, 'accounts/profile.html', {'user': user, 'posts': posts, 'is_following': is_following})


class UserPasswordRestView(auth_views.PasswordResetView):
    template_name = 'accounts/password_reset_form.html'
    success_url = reverse_lazy('accounts:password_reset_done')
    email_template_name = 'accounts/password_reset_email.html'


class UserPasswordRestDoneView(auth_views.PasswordResetDoneView):
    template_name = 'accounts/password_reset_done.html'


class UserPasswordRestConfirmView(auth_views.PasswordResetConfirmView):
    template_name = 'accounts/password_reset_confirm.html'
    success_url = reverse_lazy('accounts:password_reset_complete')


class UserPasswordResetCompleteView(auth_views.PasswordResetCompleteView):
    template_name = 'accounts/password_reset_complete.html'


class UserFollowView(LoginRequiredMixin, View):
    def get(self, request, user_id):
        user = User.objects.get(id=user_id)
        relation = Relation.objects.filter(from_user=request.user, to_user=user)
        if relation.exists():
            messages.error(request, 'you are following this user', 'danger')
        else:
            Relation(from_user=request.user, to_user=user).save()
            messages.success(request, 'you followed this user', 'success')
        return redirect('accounts:user_profile', user.id)


class UserUnfollowView(LoginRequiredMixin, View):
    def get(self, request, user_id):
        user = User.objects.get(id=user_id)
        relation = Relation.objects.filter(from_user=request.user, to_user=user)
        if relation.exists():
            relation.delete()
            messages.success(request, 'you unfollowed this user', 'success')
        else:
            messages.error(request, 'you are not following this user', 'danger')
        return redirect('accounts:user_profile', user.id)

A/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
  
   <h3 style="color:white;">
        User Login
    </h3>
    </br>

    <form action="" method="post" class="col-md-4" style="color:white;">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Login">
    </form>
</div>

{% endblock %}

A/accounts/templates/accounts/password_reset_complete.html
{% extends 'base.html' %}

{% block content %}
    <p style="color:white;">your password changed.</p>
{% endblock %}

A/accounts/templates/accounts/password_reset_confirm..html
{% extends 'base.html' %}

{% block content %}
<div>

   <h3 style="color:white;">
       Enter your email to reset password.
    </h3>
    </br>
{% if validlink %}
      <form action="" method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <input type="submit" value="Change">
      </form>
  {% else %}
      <p>This link is not valid. Please try again. </p>
  {% endif %}
</div>
{% endblock %}

A/accounts/templates/accounts/password_reset_confirm.html
{% extends 'base.html' %}

{% block content %}
<div>

   <h3 style="color:white;">
       Enter your email to reset password.
    </h3>
    </br>
{% if validlink %}
      <form action="" method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <input type="submit" value="Change">
      </form>
  {% else %}
      <p style="color:white;">This link is not valid. Please try again. </p>
  {% endif %}
</div>
{% endblock %}

A/accounts/templates/accounts/password_reset_done.html
{% extends 'base.html' %}

{% block content %}
<br/><br/>
<div>
  <h3 style="color:white;">  sent you an email.</h3>
</div>
{% endblock %}

A/accounts/templates/accounts/password_reset_email.html
Someone asked for password reset for email {{ email }}. Follow the link below:

{{ protocol}}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

A/accounts/templates/accounts/password_reset_form.html
{% extends 'base.html' %}

{% block content %}
<div>

   <h3 style="color:white;">
       Enter your email to reset password.
    </h3>
    </br>

    <form action="" method="post" class="col-md-4" style="color:white;">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="send">
    </form>
</div>
{% endblock %}

A/accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

    <div class="jumbotron">
        <h1 class="text-center">{{ user.username }}</h1>
        {% if request.user.id == user.id %}
            <a href="{% url 'home:post_create' %}" class="btn btn-primary">Create new post</a>
        {% endif %}
        {% if request.user.id != username.id and not is_following %}
            <a class="btn btn-primary" href="{% url 'accounts:user_follow' user.id %}">Follow</a>
        {% elif request.user.id != username.id and is_following %}
            <a class="btn btn-danger" href="{% url 'accounts:user_unfollow' user.id %}">Unfollow</a>
        {% endif %}
        <br><br>
        <table class="table table-dark">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">Updated</th>
                    {% if request.user.id == user.id %}
                    <th scope="col">Delete</th>
                    {% endif %}
                </tr>
            </thead>
        <tbody>
            {% for post in posts %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td><a href="{{ post.get_absolute_url }}"> {{ post.body|truncatewords:8 }} </a></td>
                    <td>{{ post.updated|date:"Y-M" }}</td>
                    {% if request.user.id == user.id %}
                    <td><a href="{% url 'home:post_delete' post.id %}">delete</a></td>
                    {% endif %}
                </tr>
            {% endfor %}
        </tbody>
</table>


{% endblock %}

A/accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>

   <h3 style="color:white;">
        User Register
    </h3>
    </br>

    <form action="" method="post" class="col-md-4" style="color:white;">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="register">
    </form>
</div>

{% endblock %}